// Persist a summary generated by the calling agent (e.g. Claude Desktop)
// to an existing Video row. Matches the shape the in-app summary pipeline
// writes in client/src/lib/services/learning.ts so both paths produce the
// same DB state.
//
// Note: this tool does NOT build the BM25 retrieval index on
// transcriptSegments. The in-app chat won't get Contextual Retrieval
// anchors for summaries generated this way. That's fine — these summaries
// are for the frontier-path UX (Claude Desktop), and if the user later
// wants in-app BM25 they can regenerate from the UI.

import { z } from 'zod';
import type { ToolDef } from '../registry';

const SectionSchema = z.object({
  heading: z.string().min(1).max(200),
  body: z.string().min(1).max(2000),
  timeSec: z.number().int().min(0).optional(),
});

const TakeawaySchema = z.object({
  text: z.string().min(1).max(280),
});

const ActionStepSchema = z.object({
  title: z.string().min(1).max(120),
  body: z.string().min(1).max(600),
});

const schema = z.object({
  videoId: z
    .string()
    .min(1)
    .describe('youtubeVideoId or Strapi documentId of an existing Video row.'),
  summaryTitle: z.string().min(1).max(200),
  summaryDescription: z.string().min(1).max(500),
  summaryOverview: z.string().min(1).describe('Markdown TL;DR — 1–2 paragraphs.'),
  keyTakeaways: z.array(TakeawaySchema).min(1).max(10),
  sections: z.array(SectionSchema).min(1).max(20),
  actionSteps: z.array(ActionStepSchema).min(1).max(10),
  aiModel: z
    .string()
    .max(100)
    .optional()
    .describe('Model that produced the summary (e.g. "claude-sonnet-4-6"). Stored verbatim.'),
});

export const saveSummaryTool: ToolDef<z.infer<typeof schema>> = {
  name: 'saveSummary',
  description:
    'Persist an AI-generated summary (title, description, overview, sections with optional timecodes, key takeaways, action steps) to an existing Video. Use this after generating a summary with a frontier model so it shows up in the app UI alongside locally-generated ones.',
  schema,
  execute: async (args, { strapi }) => {
    let video = (await strapi.documents('api::video.video').findFirst({
      filters: { youtubeVideoId: { $eq: args.videoId } },
    })) as { documentId: string } | null;

    if (!video) {
      video = (await strapi.documents('api::video.video').findOne({
        documentId: args.videoId,
      })) as { documentId: string } | null;
    }

    if (!video) {
      return { error: `No video found for "${args.videoId}". Call addVideo first.` };
    }

    const updated = await strapi.documents('api::video.video').update({
      documentId: video.documentId,
      data: {
        summaryStatus: 'generated',
        summaryTitle: args.summaryTitle,
        summaryDescription: args.summaryDescription,
        summaryOverview: args.summaryOverview,
        summaryGeneratedAt: new Date().toISOString(),
        aiModel: args.aiModel ?? null,
        keyTakeaways: args.keyTakeaways,
        sections: args.sections,
        actionSteps: args.actionSteps,
      } as Record<string, unknown>,
    });

    return {
      videoDocumentId: (updated as { documentId: string }).documentId,
      youtubeVideoId: args.videoId,
      summaryStatus: 'generated',
      sectionCount: args.sections.length,
      takeawayCount: args.keyTakeaways.length,
      actionStepCount: args.actionSteps.length,
    };
  },
};
