/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as NewPostRouteImport } from './routes/new-post'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as DigestsRouteImport } from './routes/digests'
import { Route as DigestRouteImport } from './routes/digest'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideoDocumentIdRouteImport } from './routes/video.$documentId'
import { Route as LearnVideoIdRouteImport } from './routes/learn.$videoId'
import { Route as ApiDigestChatRouteImport } from './routes/api.digest-chat'
import { Route as ApiChatRouteImport } from './routes/api.chat'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const NewPostRoute = NewPostRouteImport.update({
  id: '/new-post',
  path: '/new-post',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DigestsRoute = DigestsRouteImport.update({
  id: '/digests',
  path: '/digests',
  getParentRoute: () => rootRouteImport,
} as any)
const DigestRoute = DigestRouteImport.update({
  id: '/digest',
  path: '/digest',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoDocumentIdRoute = VideoDocumentIdRouteImport.update({
  id: '/video/$documentId',
  path: '/video/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnVideoIdRoute = LearnVideoIdRouteImport.update({
  id: '/learn/$videoId',
  path: '/learn/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDigestChatRoute = ApiDigestChatRouteImport.update({
  id: '/api/digest-chat',
  path: '/api/digest-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/digest': typeof DigestRoute
  '/digests': typeof DigestsRoute
  '/feed': typeof FeedRoute
  '/new-post': typeof NewPostRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/digest-chat': typeof ApiDigestChatRoute
  '/learn/$videoId': typeof LearnVideoIdRoute
  '/video/$documentId': typeof VideoDocumentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/digest': typeof DigestRoute
  '/digests': typeof DigestsRoute
  '/feed': typeof FeedRoute
  '/new-post': typeof NewPostRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/digest-chat': typeof ApiDigestChatRoute
  '/learn/$videoId': typeof LearnVideoIdRoute
  '/video/$documentId': typeof VideoDocumentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/digest': typeof DigestRoute
  '/digests': typeof DigestsRoute
  '/feed': typeof FeedRoute
  '/new-post': typeof NewPostRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/digest-chat': typeof ApiDigestChatRoute
  '/learn/$videoId': typeof LearnVideoIdRoute
  '/video/$documentId': typeof VideoDocumentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/digest'
    | '/digests'
    | '/feed'
    | '/new-post'
    | '/search'
    | '/settings'
    | '/api/chat'
    | '/api/digest-chat'
    | '/learn/$videoId'
    | '/video/$documentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/digest'
    | '/digests'
    | '/feed'
    | '/new-post'
    | '/search'
    | '/settings'
    | '/api/chat'
    | '/api/digest-chat'
    | '/learn/$videoId'
    | '/video/$documentId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/digest'
    | '/digests'
    | '/feed'
    | '/new-post'
    | '/search'
    | '/settings'
    | '/api/chat'
    | '/api/digest-chat'
    | '/learn/$videoId'
    | '/video/$documentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DigestRoute: typeof DigestRoute
  DigestsRoute: typeof DigestsRoute
  FeedRoute: typeof FeedRoute
  NewPostRoute: typeof NewPostRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiDigestChatRoute: typeof ApiDigestChatRoute
  LearnVideoIdRoute: typeof LearnVideoIdRoute
  VideoDocumentIdRoute: typeof VideoDocumentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-post': {
      id: '/new-post'
      path: '/new-post'
      fullPath: '/new-post'
      preLoaderRoute: typeof NewPostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digests': {
      id: '/digests'
      path: '/digests'
      fullPath: '/digests'
      preLoaderRoute: typeof DigestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digest': {
      id: '/digest'
      path: '/digest'
      fullPath: '/digest'
      preLoaderRoute: typeof DigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/$documentId': {
      id: '/video/$documentId'
      path: '/video/$documentId'
      fullPath: '/video/$documentId'
      preLoaderRoute: typeof VideoDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$videoId': {
      id: '/learn/$videoId'
      path: '/learn/$videoId'
      fullPath: '/learn/$videoId'
      preLoaderRoute: typeof LearnVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/digest-chat': {
      id: '/api/digest-chat'
      path: '/api/digest-chat'
      fullPath: '/api/digest-chat'
      preLoaderRoute: typeof ApiDigestChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DigestRoute: DigestRoute,
  DigestsRoute: DigestsRoute,
  FeedRoute: FeedRoute,
  NewPostRoute: NewPostRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiDigestChatRoute: ApiDigestChatRoute,
  LearnVideoIdRoute: LearnVideoIdRoute,
  VideoDocumentIdRoute: VideoDocumentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
